import 'package:heroicons_animated/src/icons/icon_base.dart';

const adjustmentsHorizontal = HeroiconAnimatedIconData(
  name: 'adjustments-horizontal',
  elements: [
    LineElement(
      x1: 10.5,
      y1: 6,
      x2: 20.25,
      y2: 6,
      animation: PathLengthAnimation(
        from: 1.0,
        to: 0.6923076923,
        fromOffset: 0.0,
        toOffset: 0.3076923077,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 3.75,
      y1: 6,
      x2: 10.5,
      y2: 6,
      animation: PathLengthAnimation(
        from: 0.5555555556,
        to: 1.0,
        fromOffset: 0.0,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    CircleElement(
      cx: 9,
      cy: 6,
      r: 1.5,
      animation: TranslateAnimation(
        fromX: 0.0,
        fromY: 0.0,
        toX: 3.0,
        toY: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 13.5,
      y1: 12,
      x2: 20.25,
      y2: 12,
      animation: PathLengthAnimation(
        from: 0.5555555556,
        to: 1.0,
        fromOffset: 0.4444444444,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 3.75,
      y1: 12,
      x2: 13.5,
      y2: 12,
      animation: PathLengthAnimation(
        from: 1.0,
        to: 0.6923076923,
        fromOffset: 0.0,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    CircleElement(
      cx: 15,
      cy: 12,
      r: 1.5,
      animation: TranslateAnimation(
        fromX: 0.0,
        fromY: 0.0,
        toX: -3.0,
        toY: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 10.5,
      y1: 18,
      x2: 20.25,
      y2: 18,
      animation: PathLengthAnimation(
        from: 1.0,
        to: 0.6923076923,
        fromOffset: 0.0,
        toOffset: 0.3076923077,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 3.75,
      y1: 18,
      x2: 10.5,
      y2: 18,
      animation: PathLengthAnimation(
        from: 0.5555555556,
        to: 1.0,
        fromOffset: 0.0,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    CircleElement(
      cx: 9,
      cy: 18,
      r: 1.5,
      animation: TranslateAnimation(
        fromX: 0.0,
        fromY: 0.0,
        toX: 3.0,
        toY: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
  ],
);
