import 'package:heroicons_animated/src/icons/icon_base.dart';

const adjustmentsVertical = HeroiconAnimatedIconData(
  name: 'adjustments-vertical',
  elements: [
    LineElement(
      x1: 6,
      y1: 3.75,
      x2: 6,
      y2: 13.5,
      animation: PathLengthAnimation(
        from: 1.0,
        to: 0.6923076923,
        fromOffset: 0.0,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 6,
      y1: 13.5,
      x2: 6,
      y2: 20.25,
      animation: PathLengthAnimation(
        from: 0.5555555556,
        to: 1.0,
        fromOffset: 0.4444444444,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    CircleElement(
      cx: 6,
      cy: 15,
      r: 1.5,
      animation: TranslateAnimation(
        fromX: 0.0,
        fromY: 0.0,
        toX: 0.0,
        toY: -3.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 12,
      y1: 3.75,
      x2: 12,
      y2: 10.5,
      animation: PathLengthAnimation(
        from: 0.5555555556,
        to: 1.0,
        fromOffset: 0.0,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 12,
      y1: 10.5,
      x2: 12,
      y2: 20.25,
      animation: PathLengthAnimation(
        from: 1.0,
        to: 0.6923076923,
        fromOffset: 0.0,
        toOffset: 0.3076923077,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    CircleElement(
      cx: 12,
      cy: 9,
      r: 1.5,
      animation: TranslateAnimation(
        fromX: 0.0,
        fromY: 0.0,
        toX: 0.0,
        toY: 3.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 18,
      y1: 3.75,
      x2: 18,
      y2: 13.5,
      animation: PathLengthAnimation(
        from: 1.0,
        to: 0.6923076923,
        fromOffset: 0.0,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    LineElement(
      x1: 18,
      y1: 13.5,
      x2: 18,
      y2: 20.25,
      animation: PathLengthAnimation(
        from: 0.5555555556,
        to: 1.0,
        fromOffset: 0.4444444444,
        toOffset: 0.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
    CircleElement(
      cx: 18,
      cy: 15,
      r: 1.5,
      animation: TranslateAnimation(
        fromX: 0.0,
        fromY: 0.0,
        toX: 0.0,
        toY: -3.0,
        duration: Duration(milliseconds: 500),
        delay: Duration(milliseconds: 0),
        curve: Curves.easeInOut,
      ),
    ),
  ],
);
